os: Visual Studio 2017
version: '2.10.0.{build}'
skip_tags: true

install:
- dotnet tool install fake-cli -g
- choco install --no-progress BCC-MSBuildLog
- choco install --no-progress BCC-Submission
- ps: |
    $full_build = Test-Path env:GHFVS_KEY
    $forVSInstaller = $env:BUILD_TYPE -eq "vsinstaller"
    $forPackage = $env:BUILD_TYPE -eq "package"
    $package = $full_build -and ($env:APPVEYOR_PULL_REQUEST_NUMBER -or $forVSInstaller -or $forPackage)

    $message = "Building "
    if ($package) { $message += "and packaging "}
    $message += "version " + $env:APPVEYOR_BUILD_NUMBER + " "

    if ($full_build) { $message += "(full build)" } else { $message += "(partial build)" }
    if ($forVSInstaller) { $message += " for the VS installer" }
    Write-Host $message

    git submodule init
    git submodule sync

    if ($full_build) {
      $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
      $fileContent += $env:GHFVS_KEY.Replace(' ', "`n")
      $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
      Set-Content c:\users\appveyor\.ssh\id_rsa $fileContent
    } else {
      git submodule deinit script
    }

    git submodule update --recursive --force
    nuget restore GitHubVS.sln

build_script:
- ps: >-
    fake run Build.fsx

test:
  categories:
    except:
      - Timings

on_success:
- ps: |
    if ($package) {
      Write-Host "Signing and packaging"
      script\Sign-Package -AppVeyor -ForVSInstaller:$forVSInstaller
    }

for:
-
  branches:
    except:
      - /releases/.*-vsinstaller/
  environment:
    matrix:
      - BUILD_TYPE: normal
-
  branches:
    only:
      - /releases/.*-vsinstaller/
  environment:
    matrix:
      - BUILD_TYPE: package
      - BUILD_TYPE: vsinstaller
-
  branches:
    only:
      - master
      - /releases/(?:(?!-vsinstaller).)*?/
  environment:
    matrix:
      - BUILD_TYPE: package
